### ISSUE TITLE
revH_compat - Slow command processing

### ISSUE THREAD

**Issue by jaycedowell** [lwa-project/analog_signal_processor#10]
It takes about ~~5~~ 6 s for a command to go through.

**Comment by jaycedowell** [comment]
@ProfundityOfScope Do you happen to remember why we switched away from `set_all_different_chan_cfg()` in this block?

https://github.com/lwa-project/analog_signal_processor/blob/revH_compat/aspRS485.py#L147

**Comment by ProfundityOfScope** [comment]
I believe at the time that command was broken and just led to infinite waiting. I think we eventually sourced it to a problem in lwautils

**Comment by jaycedowell** [comment]
Thanks, I had forgotten about that problem.

**Comment by jaycedowell** [comment]
Fixed with #13.
